on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout merge commit
        uses: actions/checkout@v3

      - name: Configure git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "${GITHUB_ACTOR}"

      - name: Install nix
        uses: cachix/install-nix-action@v22

      - name: Update flake inputs
        run: nix flake update --commit-lock-file

      - name: Check whether the flake evaluates and run its tests
        run: nix flake check

      - name: Push updates
        run: git push
