on:
  workflow_call:

jobs:
  update:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: git config --global user.email "actions@github.com"
      - run: git config --global user.name "${GITHUB_ACTOR}"
      - uses: DeterminateSystems/nix-installer-action@v6
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix flake update --commit-lock-file
      - run: nix flake check --all-systems
      - run: git push
