on:
  workflow_call:
    inputs:
      cachix-cache:
        type: string
        default: ""
    secrets:
      cachix-token:
        required: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/flake-checker-action@v5
      - uses: DeterminateSystems/nix-installer-action@v7
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v12
        if: ${{ inputs.cachix-cache }}
        with:
          name: ${{ inputs.cachix-cache }}
          authToken: ${{ secrets.cachix-token }}
      - run: nix flake metadata
      - run: nix flake show
      - run: nix flake check --keep-going
      - run: nix build --print-build-logs
