on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/flake-checker-action@v5
      - uses: DeterminateSystems/nix-installer-action@v6
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix flake metadata
      - run: nix flake show
      - run: nix flake check --keep-going
      - run: nix build --print-build-logs
