on:
  workflow_call:
    inputs:
      cachix-cache:
        type: string
        default: ""
      runs-on:
        type: string
        default: ubuntu-22.04
      update:
        type: boolean
        default: false
    secrets:
      cachix-token:
        required: false

jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - run: git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
      - run: git config --global user.name "${GITHUB_ACTOR}"
      - uses: DeterminateSystems/flake-checker-action@v5
      - uses: DeterminateSystems/nix-installer-action@v9
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v14
        if: ${{ inputs.cachix-cache }}
        with:
          name: ${{ inputs.cachix-cache }}
          authToken: ${{ secrets.cachix-token }}
      - run: nix flake metadata
      - run: nix flake show
      - if: ${{ inputs.update }}
        run: nix flake update --commit-lock-file
      - run: nix flake check --keep-going --all-systems
      - run: nix build --print-build-logs
      - if: ${{ inputs.update }}
        run: git push
      - run: echo "path=$(readlink result)" >> $GITHUB_ENV
      - run: echo "name=$(basename $(readlink result))" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.name }}
          path: ${{ env.path }}
