on:
  workflow_call:
    inputs:
      commit-message:
        type: string
        default: "Update pre-commit"
      update:
        type: boolean
        default: false

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
    - run: git config --global user.name "${GITHUB_ACTOR}"
    - uses: actions/setup-python@v5
    - uses: pre-commit/action@v3.0.0
    - run: git commit -a -m ${{ inputs.message }}
    - if: ${{ inputs.update }}
      run: git push
