on:
  workflow_call:
    inputs:
      commit-message:
        type: string
        default: "chore: pre-commit"
      update:
        type: boolean
        default: false
      push:
        type: boolean
        default: false
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
    - run: git config --global user.name "${GITHUB_ACTOR}"
    - uses: actions/setup-python@v5
      with:
        cache: pip
    - run: python -m pip install pre-commit
    - run: python -m pip freeze --local
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        save-always: true
    - if: ${{ inputs.update }}
      run: pre-commit autoupdate --freeze
    - run: pre-commit run --all-files --show-diff-on-failure --color=always
      continue-on-error: true
    - run: pre-commit install
    - if: ${{ inputs.push }}
      run: |
        if ! git diff --quiet; then
          git commit -am "${{ inputs.commit-message }}"
          git push
        fi
    - if: always()
      run: pre-commit run
